dist: xenial
language: python
python:
  - 3.6

before_install:
  - pip install poetry
install:
  - poetry install

before_script:
  - cp .env-sample .env

script:
  - cd revolutiontech
  - poetry run python manage.py migrate
  - poetry run coverage run ./manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
